name: octotype
version: 0.9.1
summary: A typing trainer for your terminal
description: |
  OctoType is a TUI typing trainer made with Ratatui, powered by Gladius.
  Heavily inspired by Monkeytype, with a focus on customizability.
grade: stable
confinement: devmode
base: core22

architectures:
  - build-on: amd64

parts:
  octotype:
    plugin: dump
    source: .
    source-type: local
    stage:
      - usr/
    prime:
      - usr/

apps:
  octotype:
    command: usr/bin/octotype
